# Generated by Django 4.2.5 on 2023-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Новая'), ('USED_LIKE_NEW', 'Б/У - Как новая'), ('USED_GOOD', 'Б/У - Хорошая'), ('USED_FAIR', 'Б/У - Удовлетворительная')], default='NEW', max_length=13),
        ),
    ]
